import Head from 'next/head'
import Image from 'next/image'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillTwitterCircle,
} from "react-icons/ai";
import { FaConnectdevelop } from 'react-icons/fa';
import marta from "../public/marta-foto.jpg";
import web1 from "../public/web-1.jpg";
import web2 from "../public/web-2.jpg";
import web3 from "../public/web-3.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Marta Karaba Web Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <div className="text-center p-10">
            <h2 className="text-3xl py-5 md:text-6xl text-red-500 font-bold">Hello World!</h2>
            <h3 className="text-2xl py-2 md:text-2xl">I'm a web developer, and I love what I do.</h3>
          </div>
          <div >
            <Image src={marta} alt="a photo of me" className="w-50 h-50 mx-auto m-10 rounded-full relative overflow-hidden lg:w-80 lg:h-80" />
          </div>
          <div className="text-4xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://github.com/martalexaa" target="blank"><AiFillGithub /></a>
            <a href="https://www.linkedin.com/in/m%C3%A1rta-alexandra-m%C3%B3csai-karaba-a3610b" target="blank"><AiFillLinkedin /></a>
            <a href="https://twitter.com/MartaKaraba" target="blank"><AiFillTwitterCircle /></a>
          </div>
        </section>

        <section>
          <div className="lg:px-40 text-center">
            <h3 className="text-3xl lg:text-4xl p-5  text-sky-800 font-medium">My name is Marta. Nice to meet you.</h3>
            <p className="text-md py-2 leading-8 pb-10 lg:text-xl">
              I'm currently seeking a hybrid full-time position in Berlin or remote work from anywhere.</p>
            <p className="text-md py-2 leading-8 pb-10 lg:text-xl">
              My goal is to bring expertise and passion for web development to a team that values collaboration,
              creativity, and continuous learning.
              I'm committed to delivering high-quality, maintainable, and efficient code.
              Dedicated to staying up-to-date with the latest tools and technologies,
              I approach every challenge with curiosity and enthusiasm.
              As a team player, I'm eager to learn from and contribute to my colleagues,
              while maintaining a high level of independence and demand for quality in my work.
            </p>
          </div>
        </section>

        <section id="dev-skills">
          <h3 className="text-3xl lg:text-6xl py-20 pt-10 text-center text-red-500 font-bold">My Toolbox</h3>
          <div className="flex justify-center p-30">
            <div className="text-center flex flex-row flex-wrap justify-start mb-8 lg:w-2/5">
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">html</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">css</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">javascript</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">typescript</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">jquery</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">react</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">next.js</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">tailwind</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">bootstrap</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">sass</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">aws</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">serverless</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">node</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">express</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">mongodb</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">sql</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">MERN</div>
              <div className="m-1 p-2 flex-grow bg-gray-700 text-white uppercase text-xl">git</div>
            </div>
          </div>
          <div className="flex justify-center">
            <div className="m-1 p-2 bg-red-500 text-white uppercase text-xl invisible">download resume</div>
          </div>
        </section>

        <section>
          <div className="lg:flex gap-10">

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                I'm a certified developer
              </h3>
              <p className="py-2">
                I completed a six-month full-stack web development course, with the guidance of a tutor and mentor,
                and gained a strong foundation in HTML, CSS, and JavaScript, as well as experience with some more advanced tools.
                Becoming a web developer was the journey of my life which I truly enjoyed!
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                I have experience
              </h3>
              <p className="py-2">
                I worked as a freelance translator for several years, which taught me skills such as effective communication with clients,
                meeting deadlines, and the ability to work independently.
                I also worked as a customer service agent in e-commerce at a multinational company where I had the chance to be part of a bigger team.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">

              <h3 className="text-lg font-medium pt-8 pb-2  ">
                I have a university degree
              </h3>
              <p className="py-2">
                My academic background helps me to independently search and critically evaluate information.
                It also brings me in a good position to think outside the box when facing technical challenges.
                Studying and learning new skills was always a priority in my life.
              </p>
            </div>
          </div>
          <div>

            <h3 className="text-3xl lg:text-6xl py-20 text-center text-red-500 font-bold ">My Works</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 border-solid border-2 p-2 rounded-xl bg-red-200">
              <Image src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive" />
              <p className="pt-2 pb-2 text-gray-600">The Meet App is a serverless, progressive web application (PWA) with React using a
                test-driven development (TDD) technique.
                The application uses the Google Calendar API to fetch upcoming events
                and allows users to search for a city and get a list of events hosted in that city.</p>
              <div className="flex justify-between px-20">
                <a href="https://martalexaa.github.io/meet/" target="blank"
                  className="text-center cursor-pointer text-gray-600 underline">DEMO</a>
                <a href="https://github.com/martalexaa/meet" target="blank"
                  className="text-center cursor-pointer text-gray-600 underline">CODE</a>
              </div>
            </div>
            <div className="basis-1/3 flex-1 border-solid border-2 p-2 rounded-xl bg-red-200">
              <Image src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive" />
              <p className="pt-2 pb-2 text-gray-600">The Movie App allows users to log in and read information about movies,
                and add some of them to their favorites.
                It uses a REST API to handle data and is built using MERN stack technologies, which include MongoDB, Express, React, and Node.js.</p>
              <div className="flex justify-between px-20">
                <a href="https://martalexaa-movie-app.netlify.app/signup" target="blank"
                  className="text-center cursor-pointer text-gray-600 underline">DEMO</a>
                <a href="https://github.com/martalexaa/myFlix-client"
                  target="blank"
                  className="text-center cursor-pointer text-gray-600 underline">CODE</a>
              </div>
            </div>
            <div className="basis-1/3 flex-1 border-solid border-2 p-2 rounded-xl bg-red-200">
              <Image src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive" />
              <p className="pt-2 pb-2 text-gray-600">The Pokedex is a small web application created as part of CareerFoundry's Full-Stack Web Development course with HTML, CSS, JavaScript, Bootstrap and jQuery that loads data from an external API and enables the viewing of data points in detail.
                The goal of this project was to learn basic JavaScript (variables, functions, arrays, DOM interaction, AJAX, Json etc.).
              </p>
              <div className="flex justify-between px-20">
                <a href="https://martalexaa.github.io/pokedex-app" target="blank"
                  className="text-center cursor-pointer text-gray-600 underline">DEMO</a>
                <a href="https://github.com/martalexaa/pokedex-app" target="blank"
                  className="text-center cursor-pointer text-gray-600 underline">CODE</a>
              </div>
            </div>
            <div className="basis-1/3 flex-1 border-solid border-2 p-2 rounded-xl bg-red-200">
              <Image src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive" />
              <p className="pt-2 pb-2 text-gray-600">A serverless, progressive web application (PWA) with React using a test-driven development (TDD) technique.
                The application uses the Google Calendar API to fetch upcoming events.
                This Meet App will allow users to search for a city and get a list of events hosted in that city.</p>
              <div className="flex justify-between px-20">
                <p className="text-center cursor-pointer text-gray-600 underline">DEMO</p>
                <p className="text-center cursor-pointer text-gray-600 underline">CODE</p>
              </div>
            </div>

          </div>
        </section>

        <section>
          <h3 className="text-3xl lg:text-6xl py-20 text-center text-red-500 font-bold ">Contact</h3>
          <div className="p-30 text-center m-30">
            <h3 className="text-2xl py-2 md:text-2xl">Are you interested in working with me? Let's get in touch!</h3>
            <ul className="m-20 text-xl">
              <li className="mb-3">martalexa@gmail.com</li>
              <li className="mb-3">Skype: live:martalexa_2</li>
              <li className="mb-3">+49 1234567</li>
            </ul>
            <div className="text-4xl flex justify-center gap-16 py-3 text-gray-600">
              <a href="https://github.com/martalexaa" target="blank"><AiFillGithub /></a>
              <a href="https://www.linkedin.com/in/m%C3%A1rta-alexandra-m%C3%B3csai-karaba-a3610b" target="blank"><AiFillLinkedin /></a>
              <a href="https://twitter.com/MartaKaraba" target="blank"><AiFillTwitterCircle /></a>
            </div>
          </div>
        </section>

        <footer className="mb-10">
          <div className="p-30 text-center m-30">
            <p>Created with Next.js and Tailwind CSS by Marta Karaba.</p>
            <a href="#" className="underline">Impressum</a>
          </div>
        </footer>
      </main>
    </>
  )
}
